### ISSUE TITLE
Teleport to coords

### ISSUE THREAD

**Issue by DarthVapers** [VORPCORE/vorp_admin#1]
Teleport to coords does nothing, doesn't open a input box to enter the coords to go to. Can hear the action of menu selection. All other functions/features are working.

**Comment by outsider31000** [comment]
read the dependencies needed in the `readme` file you must update all those scripts

**Comment by outsider31000** [comment]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/87246847/176997504-7a8423ac-637d-4de2-84dd-65c3b9619f27.png">
