### ISSUE TITLE
Error after input, Warn/Unwarn

### ISSUE THREAD

**Issue by pepski1270** [VORPCORE/vorp_admin#19]
![image](https://user-images.githubusercontent.com/104223970/185654978-f82ed94b-4f36-4b6f-9ee4-e88e600bdc7a.png)

**Comment by outsider31000** [comment]
![image](https://user-images.githubusercontent.com/87246847/185661115-0b143e7d-da57-48a2-9d9d-820fa5cc8c54.png)
missing  duration add , 4000)
