### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by YourgenAP** [VORPCORE/vorp_admin#3]
1) Restarted vorp_admin - I became player even though I'm owner and before restart had full admin rights. I had to relog to get my admin rights back. Please add it to README, that restarting script kills admin rights and admins have to relog to get them back;

2) Shows no active players (Should show me) - no TipRight that I'm not allowed

3) Shows no database - again no TipRight that I'm not allowed

**Comment by YourgenAP** [comment]
1) UPD: added print in admin.lua in if at line 33 - no output: neither client console, nor TipRight

**Comment by outsider31000** [comment]
no need to relog when restart script.

**Comment by outsider31000** [comment]
update the whole folder again you are clearly doing something wrong
