### ISSUE TITLE
Player list does not remove players from the list

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_admin#34]
The player list does not remove players from the list when they leave the server. If I relog 10 times, I will still appear 10 times in the list.

![Screenshot 2023-07-04 121401](https://github.com/VORPCORE/vorp_admin/assets/101003021/0cf5ddd4-05b0-45c0-a002-6be8755d2b7c)

**Comment by outsider31000** [comment]
should be fixed now
