### ISSUE TITLE
Attempt to add a 'number' with a 'string'

### ISSUE THREAD

**Issue by draobrehtom** [VORPCORE/vorp_admin#40]
```
[script:vorp_inventor] SCRIPT ERROR: @vorp_inventory/server/services/inventoryApiService.lua:70: attempt to add a 'number' with a 'string'
[script:vorp_inventor] > handler (@vorp_admin/server/server.lua:235)
[   script:vorp_admin] SCRIPT ERROR: @vorp_admin/server/server.lua:235: 
[   script:vorp_admin]  An error occurred while calling export `canCarryItem` in resource `vorp_inventory`:
[   script:vorp_admin] 
[   script:vorp_admin]  ---
```
![image](https://github.com/VORPCORE/vorp_admin/assets/6503721/d81e4546-16a7-4ac5-bc9b-7aa24b0bda8a)

![image](https://github.com/VORPCORE/vorp_admin/assets/6503721/29bebc6c-da16-4d87-9ddf-6e96f6e0f037)

![image](https://github.com/VORPCORE/vorp_admin/assets/6503721/7b661643-97f9-4224-bd60-dedf60275d59)

**Comment by outsider31000** [comment]
update inventory and vorp admin
