### ISSUE TITLE
Error after Updating Vorp-Admin

### ISSUE THREAD

**Issue by cedric1982** [VORPCORE/vorp_admin#42]
in my server console is an Error after starting "vorp-admin"

[    c-scripting-core] Creating script environments for vorp_admin 
[   script:vorp_admin] SCRIPT ERROR: @vorp_admin/server/server.lua:31: No such export ServerRpcCall in resource vorp_core 
[           resources] Started resource vorp_admin

the Resource is starting but iam wondering about this Error.

i have the latest one from github - [ script:vorp_core] Resource version Check (vorp_admin) ✅ Up to date - Version 2.4

sorry for my bad english, i hope you can help

**Comment by James-the-Coding-Gamer** [comment]
update core

**Comment by cedric1982** [comment]
core is the newest: Resource version Check (vorp_core) ✅ Up to date - Version 2.3

**Comment by James-the-Coding-Gamer** [comment]
> core is the newest: Resource version Check (vorp_core) ✅ Up to date - Version 2.3

i have looked at core and that call is there search you core files for this  

`function exports.vorp_core:ServerRpcCall()`

if you see it in core it should be working if not then your not updated 
to the newest on github

**Comment by cedric1982** [comment]
ok i downloadet the newest core and put this on the server, aber restart i became this:
`[    c-scripting-core] Creating script environments for vorp_core`
`[    script:vorp_core] SCRIPT ERROR: @vorp_core/config/commands.lua:114: attempt to index a nil value (field 'delMoney')`
`[    script:vorp_core] > fn (@vorp_core/config/commands.lua:114)`
`[           resources] Started resource vorp_core`

`[    script:vorp_core] SCRIPT ERROR: @vorp_core/server/sv_commands.lua:84: bad argument #1 to 'for iterator' (table expected, got nil)`
`[    script:vorp_core] > fn (@vorp_core/server/sv_commands.lua:84)`

**Comment by James-the-Coding-Gamer** [comment]
you did not update right just download fresh core use defaults don't edit at all not config edits and try again

**Comment by cedric1982** [comment]
ok without change the language to german, the update is perfect. no errors

**Comment by James-the-Coding-Gamer** [comment]
ok then check to make sure all langs are there for german and then just change the lang then slow add your edits till error or not error

**Comment by cedric1982** [comment]
ok after editing the config.lua with language German i bacame these errors.

**Comment by James-the-Coding-Gamer** [comment]
all you did was change from en to gr?

**Comment by cedric1982** [comment]
In the "config.lua" Line 8 i changed
`Lang = "English"`
to
`Lang = "German"`

**Comment by James-the-Coding-Gamer** [comment]
i see the issue 
the german lang is unfnished its missing things in i dont know german but i can fix with the eng trans and then google translate it lol give me a few lol

**Comment by cedric1982** [comment]
if you need help talk to me (iam german)

**Comment by James-the-Coding-Gamer** [comment]
i got it there is a PR open for it 
try that lang file

**Comment by James-the-Coding-Gamer** [comment]
https://github.com/VORPCORE/vorp-core-lua/pull/124

**Comment by James-the-Coding-Gamer** [comment]
> if you need help talk to me (iam german)



should be fixed now download core again and then try german again 

if fixed you can close the issue then :P

**Comment by cedric1982** [comment]
thank you.

**Comment by cedric1982** [comment]
Thanks
