### ISSUE TITLE
vorp_admin opening for users using /adminMenu

### ISSUE THREAD

**Issue by diogoratomas** [VORPCORE/vorp_admin#45]
![Captura de ecrã 2024-01-16 211502](https://github.com/VORPCORE/vorp_admin/assets/43974049/d48b6e1d-04ea-44ea-9d23-bfafb6d0e0f6)

**Comment by outsider31000** [comment]
you expect me to know what this image means?

**Comment by diogoratomas** [comment]
That image show the group as user but still opening the admin menu.

I taked the ace from the server.cfg.
The vorp_core commands are fine user group can't use.
The vorp_admin opens whatever the group that is set on DB

**Comment by outsider31000** [comment]
it uses 2 permissions ace or databse users table and characters table so check those as well

**Comment by diogoratomas** [comment]
I changed all to user in DB
The ace i just deleted my steam id on server.cfg
vorp_permissions don't have any modifications.

**Comment by outsider31000** [comment]
then check characters table 
and if you are the owner you always have ace permissions to remove owner permissions you need to remove fivem identifier
Owner always have ace permissions

**Comment by diogoratomas** [comment]
So because i am the owner (keymaster) i always have owner perms?

Otherwise the character and user as set to user
I don't have any identifiers registered.

**Comment by diogoratomas** [comment]
I tested in other server that i am not the owner
I have acess to vorp admin menu as user group member.

**Comment by outsider31000** [comment]
we are not responsible for how you edit your permissions. if users have permissions then edit the permissions.
